name: Test Spring Boot and Deploy postgress database

on: [push]
permissions:
  contents: read

jobs:
  
  deploy:
    name: deploy-database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: npm install
        working-directory: deployment
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: deployment
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - run: echo "jdbc:posgres://${{ steps.pulumi.outputs.pet-name }}" >> databaseurl.env
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: databseurl
          path: deployment/databaseurl.env
   
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: databseurl
      run: export DATABASE_URL=cat deployment/databaseurl.env
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
